version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      target: build
    environment:
      - APP_ENV=development.docker
    volumes:
      - ./:/go/app
      - ./.env.development.docker:/go/app/.env.development.local:cached
    tty: true
